spring:
  datasource:
    url: jdbc:mysql://115.85.181.240:3306/kotlin_spring_boot?validationQuery="select 1"&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: osean
    password: Tlatjdgjs510200!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true