spring:
  datasource:
    url: jdbc:mysql://118.67.142.31:3306/kotlin_spring_boot?validationQuery="select 1"&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: osean
    password: Tlatjdgjs510200!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
